### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by pferlito** [acquia/hydrant#47]
I'm no Node.js expert but I can't get this to work.
- Installed Simple Outh module, obtained token
- Installed Waterwheel drupal module
- Verified token is working by querying /entity/types/user?_format=json which returns 200
- Cloned this repo into <webroot>/libraries/waterwheel-js
- npm i
- npm t (all tests passed)
- Skipped npm run build (trying this in node 7.0.0)

Created the following test.js file and put it in /libraries/waterwheel-js 

```
const Waterwheel = require('./lib/waterwheel.js');

const waterwheel = new Waterwheel({base: 'http://d8-dev.site', credentials: {oauth: 'RsWv76cNKhbHTVZsGraIE88-dxKWWrBoQ34M70GLPzY'}});

waterwheel.populateResources()
  .then(res => {
    console.log(res);
  });

```

ran node test.js and got this:
(node:80914) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error
(node:80914) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
```

**Comment by mattgrill** [comment]
@pferlito Hi! Thanks for reporting this. 

Turns out this is just an unhandled rejection in your promise. As of Node 7.0.0 all unhandled rejections result in a warning, https://github.com/nodejs/node/pull/8217. 

You can do something like, 

``` javascript
waterwheel.populateResources()
  .then(res => console.log(res))
  .catch(err => console.log(err));
```

 That should capture the error and let you know what's happening without throwing a warning.

**Comment by pferlito** [comment]
@mattgrill thanks for your response. Turns out it was a configuration problem with my setup. Working smoothly now.
