### ISSUE TITLE
README needs an update

### ISSUE THREAD

**Issue by arnoldbird** [acquia/hydrant#76]
> the intent is to remove that dependency, by adding the necessary functionality to Drupal core, making that separate module ​_obsolete_​.

That module is now obsolete.

**Comment by richgerdes** [comment]
The [OpenApi module](https://www.drupal.org/project/openapi) is still a requirement for this project and has yet to be added to Drupal Core. The intent is that that move will happen eventually, but it has not happened yet. Please see my response to your question in #75.

**Comment by arnoldbird** [comment]
My bad.  I had the OpenApi module confused with the obsolete Waterwheel module.
